name: 'Jira Release Action'
description: 'A Github Action that creates Jira version, sets the given version as a fix version for provided issues, and releases the version'
branding:
  icon: "cloud"
  color: "blue"

inputs:
  domain:
    description: 'Domain name of the Jira cloud instance (e.g. your-domain.atlassian.net)'
    required: true
  username:
    description: 'Jira Username'
    required: true
  password:
    description: 'Jira Personal Access Token'
    required: true
  versionName:
    description: 'The name of the Version to use'
    required: true
  issueKeys:
    description: 'The key(s) of the issue(s) that is to be updated. If multiple are used, separate them with a comma (e.g. "TEST-1,TEST-2")'
    required: true
  versionDescription:
    description: 'The description of the Version (default: "CD version")'
    required: false
  release:
    description: 'Automatically release the version (default: false)'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
